version: "3.7"

services:
    database:
        image: postgres
        container_name: database_finapi
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=ignite123
            - POSTGRES_DB=fin_api
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: fin_api
        restart: always
        ports:
            - 3333:3333
        volumes:
            - .:/usr/apps
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local
